{% set name = "rastervision-gdal-vsi" %}
{% set version = "0.20.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rastervision_gdal_vsi-{{ version }}.tar.gz
  sha256: 0983bec863ba71d4d93d2d95058da4ed5394ac097e5059b717764e85fe1e6c21
  patches:
    - 0001-fix-imports.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - rastervision=rastervision.gdal_vsi.vsi_file_system:main

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - gdal ==3.0.4
    - python >=3.6
    - rastervision-pipeline ==0.13.1

test:
  imports:
    - rastervision.gdal_vsi
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/azavea/raster-vision
  summary: A rastervision plugin that adds a GDAL VSI file system
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - psortos
